# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gm_sWIH5SJc9ooULHOtHBUa5j7uGBFuI
"""

import pandas as pd
data = pd.read_csv("/content/avocado.csv")

print("data", data.head)
print(data.iloc[15,2])


print(data.sort_values(by="AveragePrice"))

rows= len(data.axes[0])
cols= len(data.axes[1])
print(f"rows: {rows}\ncols {cols}")


print(data["AveragePrice"].max())

print(data["AveragePrice"].min())

"""## Tarea 2"""

#Verifica la cantidad de datos que tienes, las variables que contiene cada vector de datos e identifica el tipo de variables.

data.count

"""Para describir las variables"""

data.describe().transpose()

"""Aquí podemos ver las estadisticas de cada una de las columnas, de esta manera podemos analizar que información podemos extraer de esto.

Acceder a las diferentes columnsas
"""

maximos = []
minimos= []
for column in data:
  print(data[column])
  maximos.append(max(column))
  minimos.append(min(column))

"""Esto nos da una muestra de que podemos esperar de cada columna. Podemos deducir ¿Que nos dicen estos datos? Podemos observar a grandes rasogos todos los regustrons que se han hecho sobre cada venta de aguacates. Podemos ver el número de aguacates que se vendieron por ordén, analizar el precio y hacer un monitoreo de todo esto."""

print(f"maximos {maximos}")
print(f"minimos {minimos}")

"""No es la mejor manera de hacerlo, aún así sabemos que tipo de variable tiene cada columna. """

# Basándose en la media, mediana y desviación estándar de cada variable,
# ¿Qué conclusiones puedes entregar de los datos?
prmedio= data["AveragePrice"].mean()
print(f"Mean {prmedio}")